# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
references:
  container_jdk11: &container_jdk11
    docker:
      - image: cimg/openjdk:11.0.20
    working_directory: ~/message_parser

  # Download and cache dependencies
  restore_cache_jdk11: &restore_cache_jdk11
    restore_cache:
      keys:
        - jdk11-dependencies-{{ checksum "message_parser/pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - jdk11-dependencies-

  save_cache_jdk11: &save_cache_jdk11
    save_cache:
      paths:
        - ~/jdk11
      key: jdk11-dependencies-{{ checksum "message_parser/pom.xml" }}

jobs:
  build:
    <<: *container_jdk11
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - *restore_cache_jdk11

      - run: mvn -f message_parser/pom.xml dependency:go-offline

      - *save_cache_jdk11

      # run tests!
      - run: mvn -f message_parser/pom.xml integration-test

  deploy:
    <<: *container_jdk11

    steps:
      - checkout

      # publish to clojars
      - run: mvn -s .circleci/.circleci.settings.xml -f message_parser/pom.xml deploy

      - run:
          name: Publish release
          command: |
            GITHUB_TOKEN=${GITHUB_TOKEN} sh scripts/release.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context:
            - cumulus-packages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
          context:
            - cumulus-packages