# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name:  cumulus-message-adapter-java

on: 
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        java: ['11', '17']
        javaDistribution: [ 'temurin', 'microsoft', 'corretto' ]
    name: ${{ matrix.javaDistribution }} ${{ matrix.java }} on ${{ matrix.os}} cumulus-message-adapter-java
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with: 
        distribution: ${{ matrix.javaDistribution }}
        java-version: ${{ matrix.java }}
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}/java # location for the settings.xml file
    - name: Build with Maven
      run: mvn --file message_parser/pom.xml dependency:go-offline -DjavaVersion=${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package --file task/pom.xml -DjavaVersion=${{ matrix.java }}
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        cache: 'pip'
    - name: Install Cumulus Message Adapter python requirements
      run: pip install -r message_parser/cumulus-message-adapter/requirements.txt
    - name: Test with Maven
      run: mvn --file message_parser/pom.xml integration-test -DjavaVersion=${{ matrix.java }}
    - name: Test with Maven
      run: mvn test --file task/pom.xml -DjavaVersion=${{ matrix.java }}
